services:
  postgres-userdb:
    image: postgres:16-alpine
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microreport-network

  postgres-docdb:
    image: postgres:16-alpine
    container_name: postgres_doc_db
    restart: always
    environment:
      POSTGRES_DB: doc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doc_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - doc_db_data:/var/lib/postgresql/data
    networks:
      - microreport-network

  minio:
    image: minio/minio:latest
    container_name: microreport-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - microreport-network

  user-service:
    container_name: microreport-user-service
    build:
      context: ./UserService/UserService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-userdb;Port=5432;Database=user_db;Username=postgres;Password=postgrespassword
      - JWTSettings__SecretKey=SuperSecretKeyForJWTTokenValidationMustBeLongEnough123!
      - JWTSettings__Issuer=MicroReport
      - JWTSettings__Audience=MicroReportClients
    depends_on:
      postgres-userdb:
        condition: service_healthy
    networks:
      - microreport-network

  doc-service:
    build:
      context: ./DocumentService/DocumentService
      dockerfile: Dockerfile
    container_name: doc-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # 1. Исправлено имя хоста на postgres-docdb и парам. подключения к doc_db
      - ConnectionStrings__Postgres=Host=postgres-docdb;Port=5432;Database=doc_db;Username=postgres;Password=postgrespassword
      - S3Settings__Endpoint=http://minio:9000
      - S3Settings__AccessKey=minioadmin
      # 2. Согласован пароль от MinIO
      - S3Settings__SecretKey=minioadminpassword
      - S3Settings__BucketName=documents
      # 3. Согласован SecretKey для валидации JWT
      - JwtSettings__SecretKey=SuperSecretKeyForJWTTokenValidationMustBeLongEnough123!
      #Kafka
      - Kafka__BootstrapServers=kafka:29092
      - Kafka__Topics__ReportRequested=report-requests-topic
      - Kafka__Topics__ReportCompleted=report-completed-topic
      - Kafka__GroupId=document-service-report-consumers
    depends_on:
      postgres-docdb:
        condition: service_healthy
      minio:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - microreport-network

  api-gateway:
    build:
      context: ./ApiGateway/ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:8080" # Единый порт Gateway для работы снаружи
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - user-service
      - doc-service
    networks:
      - microreport-network
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microreport-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

networks:
  microreport-network:
    driver: bridge

volumes:
  user_db_data:
    driver: local
  doc_db_data:
    driver: local
  minio_data:
    driver: local